-audiobloksLoginName admin@air.com
-audiobloksPassword Footage123!
-clientSecretFilePath /home/qnex/audioblocks-access-granting/src/main/resources/client_secret.json
-pauseTimeFrom 30
-pauseTimeTo 40
-spreadsheetId 1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms
-spreadsheetTabName "Class Data"
-datePattern dd.MM.yyyy
-adminName "Роман Шинкаренко"